Flappy Bird Game Engine: LevelManager Class Reference
LevelManager Class Reference
module level_loader
Level Manager for managing multiple levels.
Private Member Functions
this ()
void loadLevel (string filename)
void setLevel (Level level)
Level getCurrentLevel ()
void setLevelsPath (string path)
void update (double deltaTime)
void render (Renderer renderer)
Static Private Member Functions
static LevelManager Get ()
Private Attributes
Level currentLevel
string levelsPath = "levels/"
Static Private Attributes
static LevelManager instance
Detailed Description
Level Manager for managing multiple levels.
Definition at line 168 of file level_loader.d.
Constructor & Destructor Documentation
this()
LevelManager::this () inline private
Definition at line 172 of file level_loader.d.
Member Function Documentation
Get()
LevelManager LevelManager::Get () inline static private
Definition at line 174 of file level_loader.d.
References instance.
Referenced by this(), and this().
getCurrentLevel()
Level LevelManager::getCurrentLevel () inline private
Definition at line 192 of file level_loader.d.
References currentLevel.
Referenced by this(), and this().
loadLevel()
void LevelManager::loadLevel (string filename) inline private
Definition at line 181 of file level_loader.d.
References currentLevel, and levelsPath.
Referenced by this(), and this().
render()
void LevelManager::render (Renderer renderer) inline private
Definition at line 204 of file level_loader.d.
References currentLevel.
setLevel()
void LevelManager::setLevel (Level level) inline private
Definition at line 188 of file level_loader.d.
References currentLevel.
setLevelsPath()
void LevelManager::setLevelsPath (string path) inline private
Definition at line 195 of file level_loader.d.
References levelsPath.
Referenced by this(), and this().
update()
void LevelManager::update (double deltaTime) inline private
Definition at line 198 of file level_loader.d.
References currentLevel.
Field Documentation
currentLevel
Level LevelManager::currentLevel private
Definition at line 170 of file level_loader.d.
Referenced by getCurrentLevel(), loadLevel(), render(), setLevel(), and update().
instance
LevelManager LevelManager::instance static private
Definition at line 169 of file level_loader.d.
Referenced by Get().
levelsPath
string LevelManager::levelsPath = "levels/" private
Definition at line 171 of file level_loader.d.
Referenced by loadLevel(), and setLevelsPath().
The documentation for this class was generated from the following file:
src/level_loader.d