Flappy Bird Game Engine: ResourceManager Class Reference
ResourceManager Class Reference
module resource_manager
Private Member Functions
this ()
void SetRenderer (SDL_Renderer *r)
SDL_Texture * LoadTexture (string path)
SDL_Texture * GetTexture (string name)
void LoadFromJSON (string jsonPath)
bool LoadGeneric T (string name, T data)
T GetGeneric T (string name)
bool HasTexture (string name)
bool HasGeneric (string name)
void UnloadTexture (string name)
void UnloadAll ()
size_t TextureCount ()
size_t GenericResourceCount ()
~this ()
Static Private Member Functions
static ResourceManager Get ()
Private Attributes
SDL_Texture * textures
void * genericResources
SDL_Renderer * renderer
Static Private Attributes
static ResourceManager instance
Detailed Description
Definition at line 9 of file resource_manager.d.
Constructor & Destructor Documentation
this()
ResourceManager::this () inline private
Definition at line 15 of file resource_manager.d.
~this()
ResourceManager::~this () inline private
Definition at line 110 of file resource_manager.d.
References genericResources, and textures.
Member Function Documentation
GenericResourceCount()
size_t ResourceManager::GenericResourceCount () inline private
Definition at line 107 of file resource_manager.d.
References genericResources.
Get()
ResourceManager ResourceManager::Get () inline static private
Definition at line 18 of file resource_manager.d.
References instance.
Referenced by render(), GameOverScene::this(), MenuScene::this(), and this().
GetTexture()
SDL_Texture * ResourceManager::GetTexture (string name) inline private
Definition at line 45 of file resource_manager.d.
References textures.
HasGeneric()
bool ResourceManager::HasGeneric (string name) inline private
Definition at line 88 of file resource_manager.d.
References genericResources.
HasTexture()
bool ResourceManager::HasTexture (string name) inline private
Definition at line 85 of file resource_manager.d.
References textures.
LoadFromJSON()
void ResourceManager::LoadFromJSON (string jsonPath) inline private
Definition at line 50 of file resource_manager.d.
References LoadTexture().
LoadTexture()
SDL_Texture * ResourceManager::LoadTexture (string path) inline private
Definition at line 27 of file resource_manager.d.
References renderer, and textures.
Referenced by LoadFromJSON(), render(), GameOverScene::this(), and MenuScene::this().
SetRenderer()
void ResourceManager::SetRenderer (SDL_Renderer * r) inline private
Definition at line 24 of file resource_manager.d.
References r, and renderer.
T() [1/2]
T GetGeneric ResourceManager::T (string name) inline private
Definition at line 79 of file resource_manager.d.
References genericResources, and T().
T() [2/2]
bool LoadGeneric ResourceManager::T (string name, T data) inline private
Definition at line 69 of file resource_manager.d.
References genericResources, and T().
Referenced by T(), and T().
TextureCount()
size_t ResourceManager::TextureCount () inline private
Definition at line 104 of file resource_manager.d.
References textures.
UnloadAll()
void ResourceManager::UnloadAll () inline private
Definition at line 96 of file resource_manager.d.
References genericResources, and textures.
UnloadTexture()
void ResourceManager::UnloadTexture (string name) inline private
Definition at line 90 of file resource_manager.d.
References textures.
Field Documentation
genericResources
void* ResourceManager::genericResources private
Definition at line 12 of file resource_manager.d.
Referenced by GenericResourceCount(), HasGeneric(), T(), T(), UnloadAll(), and ~this().
instance
ResourceManager ResourceManager::instance static private
Definition at line 10 of file resource_manager.d.
Referenced by Get().
renderer
SDL_Renderer* ResourceManager::renderer private
Definition at line 13 of file resource_manager.d.
Referenced by LoadTexture(), and SetRenderer().
textures
SDL_Texture* ResourceManager::textures private
Definition at line 11 of file resource_manager.d.
Referenced by GetTexture(), HasTexture(), LoadTexture(), TextureCount(), UnloadAll(), UnloadTexture(), and ~this().
The documentation for this class was generated from the following file:
src/resource_manager.d