Flappy Bird Game Engine: src/scenes.d File Reference
scenes.d File Reference
module game.scenes
import resource_manager;
import bindbc.sdl;
import input;
import main_game;
import gameobject;
import std.stdio;
import level_loader;
import std.conv;
import renderer;
Data Structures
class MenuScene
Menu Scene Main menu of the game.
class GameOverScene
Game Over scene Displayed when the game ends.
Functions
this (Renderer r, string levelFile=null)
Level createDefaultLevel ()
override string getName ()
override void update (double deltaTime)
override void render (Renderer renderer)
Level getLevel ()
void setLevel (Level level)
bool isLevelComplete ()
bool hasGameFailed ()
void setGameFailed (bool failed)
int getScore ()
void addScore (int points)
Variables
MenuScene currentLevel
Gameplay Scene this is the main playing scene.
Renderer renderer
bool levelComplete = false
bool gameFailed = false
int score = 0
Function Documentation
addScore()
void addScore (int points) private
Definition at line 184 of file scenes.d.
References score.
createDefaultLevel()
Level createDefaultLevel () private
Definition at line 125 of file scenes.d.
References GameObject::addComponent(), LevelConfig::bgB, LevelConfig::bgG, LevelConfig::bgR, GameObject::getTransform(), LevelConfig::gravity, LevelConfig::height, LevelConfig::name, LevelConfig::width, TransformComponent::x, and TransformComponent::y.
Referenced by this().
getLevel()
Level getLevel () private
Definition at line 166 of file scenes.d.
References currentLevel.
getName()
override string getName () private
Definition at line 151 of file scenes.d.
getScore()
int getScore () private
Definition at line 181 of file scenes.d.
References score.
hasGameFailed()
bool hasGameFailed () private
Definition at line 175 of file scenes.d.
References gameFailed.
isLevelComplete()
bool isLevelComplete () private
Definition at line 172 of file scenes.d.
References levelComplete.
render()
override void render (Renderer renderer) private
Definition at line 159 of file scenes.d.
References currentLevel.
setGameFailed()
void setGameFailed (bool failed) private
Definition at line 178 of file scenes.d.
References gameFailed.
setLevel()
void setLevel (Level level) private
Definition at line 169 of file scenes.d.
References currentLevel.
this()
this (Renderer r, string levelFile = null) private
Definition at line 114 of file scenes.d.
References createDefaultLevel(), currentLevel, LevelManager::Get(), LevelManager::getCurrentLevel(), levelFile, LevelManager::loadLevel(), r, and LevelManager::setLevelsPath().
update()
override void update (double deltaTime) private
Definition at line 154 of file scenes.d.
References currentLevel.
Variable Documentation
currentLevel
MenuScene currentLevel
Gameplay Scene this is the main playing scene.
gameFailed
bool gameFailed = false private
Definition at line 111 of file scenes.d.
Referenced by hasGameFailed(), and setGameFailed().
levelComplete
bool levelComplete = false private
Definition at line 110 of file scenes.d.
renderer
Renderer renderer private
Definition at line 109 of file scenes.d.
Referenced by GameOverScene::render(), and MenuScene::render().
score
int score = 0 private
Definition at line 112 of file scenes.d.