Flappy Bird Game Engine: GameScript Class Reference
GameScript Class Reference
module script_system
Script file structure.
Private Member Functions
this (string scriptName)
void addCommand (ScriptCommand cmd)
ScriptCommand[] getCommands ()
void setFlag (string flagName, bool value)
bool getFlag (string flagName)
void setVariable (string varName, float value)
float getVariable (string varName)
string getName ()
void saveToFile (string filepath)
Static Private Member Functions
static GameScript loadFromFile (string filepath)
Private Attributes
string name
ScriptCommand[] commands
bool[string] flags
float[string] variables
Detailed Description
Script file structure.
Definition at line 38 of file script_system.d.
Constructor & Destructor Documentation
this()
GameScript::this (string scriptName) inline private
Definition at line 43 of file script_system.d.
References name.
Member Function Documentation
addCommand()
void GameScript::addCommand (ScriptCommand cmd) inline private
Definition at line 47 of file script_system.d.
References commands.
Referenced by loadFromFile().
getCommands()
ScriptCommand[] GameScript::getCommands () inline private
Definition at line 50 of file script_system.d.
References commands.
getFlag()
bool GameScript::getFlag (string flagName) inline private
Definition at line 58 of file script_system.d.
References flags.
getName()
string GameScript::getName () inline private
Definition at line 74 of file script_system.d.
References name.
getVariable()
float GameScript::getVariable (string varName) inline private
Definition at line 68 of file script_system.d.
References variables.
loadFromFile()
GameScript GameScript::loadFromFile (string filepath) inline static private
Definition at line 78 of file script_system.d.
References addCommand(), setFlag(), setVariable(), and value.
Referenced by loadScript().
saveToFile()
void GameScript::saveToFile (string filepath) inline private
Definition at line 146 of file script_system.d.
References commands, flags, name, value, and variables.
setFlag()
void GameScript::setFlag (string flagName, bool value) inline private
Definition at line 54 of file script_system.d.
References flags, and value.
Referenced by loadFromFile().
setVariable()
void GameScript::setVariable (string varName, float value) inline private
Definition at line 65 of file script_system.d.
References value, and variables.
Referenced by loadFromFile().
Field Documentation
commands
ScriptCommand [] GameScript::commands private
Definition at line 40 of file script_system.d.
Referenced by addCommand(), getCommands(), and saveToFile().
flags
bool [string] GameScript::flags private
Definition at line 41 of file script_system.d.
Referenced by getFlag(), saveToFile(), and setFlag().
name
string GameScript::name private
Definition at line 39 of file script_system.d.
Referenced by getName(), saveToFile(), and this().
variables
float [string] GameScript::variables private
Definition at line 42 of file script_system.d.
Referenced by getVariable(), saveToFile(), and setVariable().
The documentation for this class was generated from the following file:
src/script_system.d