Flappy Bird Game Engine: GameObject Class Reference
GameObject Class Reference
module gameobject
Main GameObject class that holds components.
Private Member Functions
this (string objName="GameObject")
void addComponent (Component component)
T getComponent (T :Component)()
TransformComponent getTransform ()
void update (double deltaTime)
void render (Renderer renderer)
void setActive (bool isActive)
bool isActive ()
string getName ()
void setName (string newName)
void destroy ()
JSONValue serialize ()
Static Private Member Functions
static GameObject deserialize (JSONValue data)
Private Attributes
Component[] components
string name
bool active = true
TransformComponent transformComponent
Detailed Description
Main GameObject class that holds components.
Definition at line 249 of file gameobject.d.
Constructor & Destructor Documentation
this()
GameObject::this (string objName = "GameObject") inline private
Definition at line 255 of file gameobject.d.
References addComponent(), name, and transformComponent.
Member Function Documentation
addComponent()
void GameObject::addComponent (Component component) inline private
Definition at line 261 of file gameobject.d.
References components.
Referenced by createDefaultLevel(), deserialize(), and this().
deserialize()
GameObject GameObject::deserialize (JSONValue data) inline static private
Definition at line 323 of file gameobject.d.
References addComponent(), getTransform(), and setActive().
Referenced by deserialize().
destroy()
void GameObject::destroy () inline private
Definition at line 305 of file gameobject.d.
References components, and transformComponent.
getComponent()
T GameObject::getComponent (T :Component) inline private
Definition at line 265 of file gameobject.d.
References components.
getName()
string GameObject::getName () inline private
Definition at line 298 of file gameobject.d.
References name.
getTransform()
TransformComponent GameObject::getTransform () inline private
Definition at line 275 of file gameobject.d.
References transformComponent.
Referenced by createDefaultLevel(), and deserialize().
isActive()
bool GameObject::isActive () inline private
Definition at line 294 of file gameobject.d.
References active.
Referenced by setActive().
render()
void GameObject::render (Renderer renderer) inline private
Definition at line 285 of file gameobject.d.
References active, and components.
serialize()
JSONValue GameObject::serialize () inline private
Definition at line 310 of file gameobject.d.
References active, components, and name.
setActive()
void GameObject::setActive (bool isActive) inline private
Definition at line 291 of file gameobject.d.
References active, and isActive().
Referenced by deserialize().
setName()
void GameObject::setName (string newName) inline private
Definition at line 301 of file gameobject.d.
References name.
update()
void GameObject::update (double deltaTime) inline private
Definition at line 279 of file gameobject.d.
References active, and components.
Field Documentation
active
bool GameObject::active = true private
Definition at line 252 of file gameobject.d.
Referenced by isActive(), render(), serialize(), setActive(), and update().
components
Component [] GameObject::components private
Definition at line 250 of file gameobject.d.
Referenced by addComponent(), destroy(), getComponent(), render(), serialize(), and update().
name
string GameObject::name private
Definition at line 251 of file gameobject.d.
Referenced by getName(), serialize(), setName(), and this().
transformComponent
TransformComponent GameObject::transformComponent private
Definition at line 253 of file gameobject.d.
Referenced by destroy(), getTransform(), and this().
The documentation for this class was generated from the following file:
src/gameobject.d